language: node_js
build:
  cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: $S3_BUCKET
  skip_cleanup: true
  acl: public_read
  local_dir: dist
  upload-dir: book
on:
  branch: master